test deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -123,6 +123,8 @@ deploy_job:
     #decode private ssh key
     - |
       mkdir -p ~/.ssh
+      echo "DEBUG base64:"
+      echo "$SSH_PRIVATE_KEY" | base64 -d > /dev/null && echo "✅ base64 is valid" || echo "❌ base64 is invalid"
       echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/gitlabrunner
       chmod 600 ~/.ssh/gitlabrunner
       eval "$(ssh-agent -s)"
